#!/bin/bash
# Kuark CLI - auto-rendered markdown views (human dashboard)
#
# Generated from state.json after every ledger event. Read-only artifacts —
# do NOT hand-edit; they get overwritten.

source "$(dirname "${BASH_SOURCE[0]}")/_common.sh"

views_render_all() {
  mkdir -p "$VIEWS_DIR"
  _render_tasks       > "$VIEWS_DIR/tasks.md"
  _render_dashboard   > "$VIEWS_DIR/dashboard.md"
  _render_by_agent    > "$VIEWS_DIR/by-agent.md"
  _render_timeline    > "$VIEWS_DIR/timeline.md"
}

# ── tasks.md ────────────────────────────────────────────────
_render_tasks() {
  local s; s=$(state_get)

  cat <<EOF
# Tasks Overview

_Last updated: $(now_iso)_
_Source: \`.swarm/ledger.jsonl\` — do not edit this file directly._

EOF

  local sprint_name
  sprint_name=$(echo "$s" | jq -r '.sprint.current.name // "No active sprint"')
  local sprint_id
  sprint_id=$(echo "$s" | jq -r '.sprint.current.id // ""')
  local sprint_goal
  sprint_goal=$(echo "$s" | jq -r '.sprint.current.goal // ""')

  echo "## Active Sprint: $sprint_id — $sprint_name"
  [ -n "$sprint_goal" ] && echo "> $sprint_goal"
  echo

  _task_section "$s" "in-progress" "🔥 In Progress" "$sprint_id"
  _task_section "$s" "review"      "👀 In Review"   "$sprint_id"
  _task_section "$s" "blocked"     "🚧 Blocked"     "$sprint_id"
  _task_section "$s" "planned"     "📋 Planned"     "$sprint_id"
  _task_section "$s" "done"        "✅ Completed"   "$sprint_id"

  echo
  echo "## Stats"
  echo "$s" | jq -r '
    .stats |
    "- **Total:** \(.tasks_total) tasks",
    "- **Done:** \(.tasks_done) · **In Progress:** \(.tasks_in_progress) · **Review:** \(.tasks_review) · **Planned:** \(.tasks_planned) · **Blocked:** \(.tasks_blocked)",
    (if .tasks_total > 0 then "- **Completion:** \((.tasks_done * 100 / .tasks_total | floor))%" else empty end)
  '
}

_task_section() {
  local s="$1" status="$2" heading="$3" sprint_filter="$4"
  local rows
  rows=$(echo "$s" | jq -r --arg st "$status" --arg sp "$sprint_filter" '
    [.tasks | to_entries[] | .value | select(.status == $st)]
    | sort_by(.created)
    | .[] |
      "| \(.id) | \(.title) | \(.assignee // "-") | \(.story // "-") | \(.priority // "-") | \(.updated[0:10]) |"
  ')
  local count
  count=$(echo "$s" | jq -r --arg st "$status" '[.tasks[] | select(.status == $st)] | length')
  [ "$count" = "0" ] && return

  echo "### $heading ($count)"
  echo
  echo "| ID | Title | Assignee | Story | Priority | Updated |"
  echo "|---|---|---|---|---|---|"
  echo "$rows"
  echo
}

# ── dashboard.md ────────────────────────────────────────────
_render_dashboard() {
  local s; s=$(state_get)

  cat <<EOF
# Kuark Dashboard

_Last updated: $(now_iso)_

## Project

EOF

  echo "$s" | jq -r '
    if .project then
      "- **Name:** \(.project.name // "?")",
      "- **Description:** \(.project.description // "-")",
      "- **Status:** \(.project.status // "active")"
    else
      "_No project initialized_"
    end
  '

  echo
  echo "## Current Agent"
  echo
  echo "$s" | jq -r '
    "- **Active:** \(.agent.current // "—")",
    "- **Previous:** \(.agent.previous // "—")"
  '

  echo
  echo "## Sprint"
  echo
  echo "$s" | jq -r '
    if .sprint.current then
      "- **\(.sprint.current.id):** \(.sprint.current.name)",
      "- **Goal:** \(.sprint.current.goal // "-")",
      "- **Started:** \(.sprint.current.started // "-")"
    else
      "_No active sprint_"
    end
  '

  echo
  echo "## Snapshot"
  echo
  echo "$s" | jq -r '.stats |
    "| Metric | Count |",
    "|---|---|",
    "| Tasks total | \(.tasks_total) |",
    "| Done | \(.tasks_done) |",
    "| In progress | \(.tasks_in_progress) |",
    "| Review | \(.tasks_review) |",
    "| Planned | \(.tasks_planned) |",
    "| Blocked | \(.tasks_blocked) |",
    "| Stories | \(.stories_total) |",
    "| Decisions | \(.decisions_total) |",
    "| Handoffs | \(.handoffs_total) |"
  '

  echo
  echo "## Recent Handoffs"
  echo
  echo "$s" | jq -r '
    .handoffs | sort_by(.ts) | reverse | .[0:5] |
    if length == 0 then "_None yet_"
    else
      ["| Time | From | To | Task | Summary |",
       "|---|---|---|---|---|"] + [
        .[] | "| \(.ts[0:16] | sub("T";" ")) | \(.from) | \(.to) | \(.task // "-") | \(.summary // "-") |"
      ]
      | .[]
    end
  '

  echo
  echo "## Open Decisions"
  echo
  echo "$s" | jq -r '
    .decisions | sort_by(.ts) | reverse | .[0:5] |
    if length == 0 then "_None yet_"
    else
      ["| ID | Topic | Outcome |", "|---|---|---|"] + [
        .[] | "| \(.id) | \(.topic) | \(.outcome // "-") |"
      ]
      | .[]
    end
  '
}

# ── by-agent.md ─────────────────────────────────────────────
_render_by_agent() {
  local s; s=$(state_get)

  cat <<EOF
# Tasks by Agent

_Last updated: $(now_iso)_

EOF

  echo "$s" | jq -r '
    .stats.by_agent | to_entries | sort_by(.key) |
    (["| Agent | Total | Done | In Progress | Planned | Done % |",
      "|---|---|---|---|---|---|"] + [
      .[] |
        "| \(.key) | \(.value.total) | \(.value.done) | \(.value.inprog) | \(.value.planned) | \(if .value.total > 0 then (.value.done * 100 / .value.total | floor) else 0 end)% |"
    ])[]
  '

  echo
  echo "## Per-Agent Task List"
  echo

  local agents agent_name
  agents=$(echo "$s" | jq -r '.stats.by_agent | keys[]')
  while IFS= read -r agent_name; do
    [ -z "$agent_name" ] && continue
    echo "### $agent_name"
    echo
    echo "| ID | Title | Status | Story | Priority |"
    echo "|---|---|---|---|---|"
    echo "$s" | jq -r --arg a "$agent_name" '
      [.tasks[] | select(.assignee == $a)] | sort_by(.id) |
      .[] | "| \(.id) | \(.title) | \(.status) | \(.story // "-") | \(.priority // "-") |"
    '
    echo
  done <<< "$agents"
}

# ── timeline.md ─────────────────────────────────────────────
_render_timeline() {
  cat <<EOF
# Activity Timeline

_Last updated: $(now_iso)_
_Most recent 50 events from \`.swarm/ledger.jsonl\`._

| Time | Type | By | Detail |
|---|---|---|---|
EOF

  [ -f "$LEDGER" ] || return

  # Show newest-first; macOS has no `tac`, so we awk-reverse
  tail -n 50 "$LEDGER" | awk '{ a[NR]=$0 } END { for (i=NR; i>=1; i--) print a[i] }' | jq -r '
    "| \(.ts[0:16] | sub("T";" ")) | \(.type) | \(.by // "system") | " + (
      if   .type == "task.create"  then "\(.data.id): \(.data.title // "")"
      elif .type == "task.update"  then "\(.data.id): \(.data.status // .data | tostring)"
      elif .type == "handoff"      then "\(.data.from) → \(.data.to)" + (if .data.task then " [\(.data.task)]" else "" end)
      elif .type == "story.create" then "\(.data.id): \(.data.title // "")"
      elif .type == "sprint.start" then "Sprint started: \(.data.name // .data.id)"
      elif .type == "sprint.end"   then "Sprint ended: \(.data.id // "")"
      elif .type == "decision"     then "\(.data.id): \(.data.topic // "")"
      elif .type == "agent.set"    then "→ \(.data.agent)"
      elif .type == "project.init" then "Project: \(.data.name // "")"
      else (.data | tostring | .[0:60]) end
    ) + " |"
  '
}
